mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
global-client-fingerprint: chrome
global-ua: clash-verge/v1.6.6
dns:
    enable: true
    ipv6: false
    default-nameserver: [223.5.5.5, 223.6.6.6]
    proxy-server-nameserver: ['https://dns.alidns.com/dns-query#h3=true', 'https://223.5.5.5/dns-query', 'https://223.6.6.6/dns-query', 'tls://dns.alidns.com', 'tls://223.5.5.5:853', 'tls://223.6.6.6:853']
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter: ['*.lan', localhost.ptlogin2.qq.com]
    use-hosts: true
    nameserver: ['https://dns.alidns.com/dns-query#h3=true', 'https://223.5.5.5/dns-query', 'https://223.6.6.6/dns-query', 'tls://dns.alidns.com', 'tls://223.5.5.5:853', 'tls://223.6.6.6:853']
    fallback: ['https://dns.alidns.com/dns-query#h3=true', 'https://223.5.5.5/dns-query', 'https://223.6.6.6/dns-query', 'tls://dns.alidns.com', 'tls://223.5.5.5:853', 'tls://223.6.6.6:853']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
